export const LOGIN_IN_PROGRESS = "LOGIN_IN_PROGRESS";
export const LOGIN_IN_SUCCESS = "LOGIN_IN_SUCCESS";
export const LOGIN_IN_ERROR = "LOGIN_IN_ERROR";
export const INITIATE_LOGOUT = "INITIATE_LOGOUT";
